GET http://localhost:5062/games

###
GET http://localhost:5062/games/1

###
POST http://localhost:5062/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genreId": 5,
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
POST http://localhost:5062/games
Content-Type: application/json

{
    "name": "Assassin's Creed IV",
    "genreId": 5,
    "price": 39.99,
    "releaseDate": "2013-11-09"
}

###
POST http://localhost:5062/games
Content-Type: application/json

{
    "name": "Call of Duty",
    "genreId": 1,
    "price": 29.99,
    "releaseDate": "2007-12-20"
}

###